#!/usr/bin/env python3
"""Embed a PNG as opaque RGB for the taskbar emblem (blended onto panel brand color)."""
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("png-to-emblem-h.py: requires python3-pillow\n")
    sys.exit(1)

# Matches rgba(30, 32, 42, ALPHA) panel fill (see br8-panel.c)
BRAND_BG = (30, 32, 42)


def blend(px, bg=BRAND_BG):
    r, g, b, a = px
    t = a / 255.0
    return (
        int(r * t + bg[0] * (1 - t)),
        int(g * t + bg[1] * (1 - t)),
        int(b * t + bg[2] * (1 - t)),
    )


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(f"usage: {sys.argv[0]} input.png output.h\n")
        sys.exit(1)
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    im = Image.open(src).convert("RGBA")
    w, h = im.size
    pixels = [blend(im.getpixel((x, y))) for y in range(h) for x in range(w)]
    lines = [
        "/* Auto-generated by scripts/png-to-emblem-h.py — do not edit */",
        f"#define EMBLEM_W {w}",
        f"#define EMBLEM_H {h}",
        "static const unsigned char emblem_rgb[] = {",
    ]
    chunk = []
    for i, (r, g, b) in enumerate(pixels):
        chunk.append(f"{r},{g},{b}")
        if len(chunk) >= 12:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    dst.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
