# Backroot 8 system neofetch defaults (see /usr/share/backroot8/neoemblem.txt)
print_config="off"
title_fqdn="off"
distro_shorthand="off"
os_arch="off"

image_backend="ascii"
image_source="/usr/share/backroot8/neoemblem.txt"
ascii_colors=(6 6 6 6 6 6 6)
colors=(6 6 6 6 6 6)
