#!/bin/bash
build() {
    add_binary /usr/bin/fbi
    add_file /usr/lib/backroot8/br8-bootscreen.sh
    if [ -f /usr/share/backroot8/bootscreen.ppm ]; then
        add_file /usr/share/backroot8/bootscreen.ppm
    fi
    if [ -f /usr/share/backroot8/bootscreen.png ]; then
        add_file /usr/share/backroot8/bootscreen.png
    fi
    add_file /etc/initcpio/hooks/br8_boot_util /usr/lib/initcpio/br8_boot_util
    add_runscript
}

help() {
    echo 'Backroot 8: framebuffer boot emblem in initramfs (before root pivot)'
}
