#!/bin/bash
build() {
    add_binary /usr/bin/fbi
    add_file /usr/lib/backroot8/br8-bootscreen.sh
    add_file /usr/share/backroot8/bootscreen.png
    add_file /etc/initcpio/hooks/br8_boot_util /usr/lib/initcpio/br8_boot_util
    add_runscript
}

help() {
    echo 'Backroot 8: framebuffer boot emblem in initramfs (before Plymouth hook)'
}
