#!/bin/bash
build() {
    add_module overlay
    # busybox mount in early initramfs does not support -t overlay
    add_binary /usr/bin/mount
    add_binary /usr/bin/modprobe
    add_file /etc/initcpio/hooks/br8_boot_util /usr/lib/initcpio/br8_boot_util
    add_runscript
}

help() {
    echo 'Backroot 8: mount overlay root before pivot'
}
